version: '3.9'
services:
  backend:
    build: .
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - .:/app
    env_file:
    - .env
    environment:
      JWTKEY: ${JWTKEY}
      DATABASE_URL: ${DATABASE_URL}
      PORT: 8000
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: gotasks
      MYSQL_USER: test
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - .dbdata:/var/lib/mysql
    ports:
    - 33066:3306