name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: 34.122.149.100
          username: salimdesk
          key: ${{ secrets.SERVER_KEY }}
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
          port: 22
      # Step 1: Checkout
      - name: Deploy to Docker swarm
        uses: wshihadeh/docker-deployment-action@v1
        with:
          remote_docker_host: user@myswarm.com
          ssh_private_key: ${{ secrets.SERVER_KEY }}
          ssh_public_key: ssh-keyscan -H 34.122.149.100
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
          deployment_mode: docker-compose
          copy_stack_file: true
          deploy_path: /my-deployment
          stack_file_name: docker-compose.yaml
          keep_files: 5
          args: my_applicaion
