name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: git clone
          
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: 34.122.149.100
          username: salimdesk
          key: ${{ secrets.SERVER_KEY }}
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
          port: 22
          script: |
           cd /
           cd my-deployment
           git clone https://github.com/salimHarthi/go_task_app
            
