name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

#     - name: Deploy to Docker compose
#       uses: wshihadeh/docker-deployment-action@v1
#       with:
#         remote_docker_host: salimdesk@34.72.147.145
#         ssh_private_key: ${{ secrets.SERVER_KEY }}
#         ssh_public_key:  ssh-keyscan -H 34.72.147.145
#         deployment_mode: docker-compose
#         copy_stack_file: true
#         deploy_path: /tmp
#         stack_file_name: docker-compose.yaml
#         keep_files: 5
#         args: up -d
#         docker_prune: 'true'
#         pull_images_first: 'true'

#  kinda works
#     - uses: alex-ac/github-action-ssh-docker-compose@master
#       name: Docker-Compose Remote Deployment
#       with:
#         ssh_host: 34.72.147.145
#         ssh_private_key: ${{ secrets.SERVER_KEY }}
#         ssh_user: salimdesk
#         docker_compose_prefix: go


       
#     - name: executing remote ssh commands using password
#       uses: appleboy/ssh-action@master
#       with:
#         host: 34.72.147.145
#         username: salimdesk
#         key: ${{ secrets.SERVER_KEY }}
#         passphrase: ""
#         port: 22
#           script: |
#            cd /
#            cd my-deployment
#            cd go_task_app
#            git pull
#            docker-compose up -d

    - name: Build image
      run: docker-compose build
    - name: save images
      run: docker images
    - name: ls
      run: ls
      
#     - name: Deploy to Server
#       uses: easingthemes/ssh-deploy@main
#       env:
#           SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
#           ARGS: "-rltgoDzvO --delete"
#           SOURCE: "/build"
#           REMOTE_HOST: 34.122.149.100
#           REMOTE_USER: salimdesk
#           TARGET: /tmp/aa
#           EXCLUDE: "/dist/, /node_modules/"
